[breaking] large refactoring of SCS.jl
jump-dev/SCS.jl pull request #218
Opened 2021-09-13 02:58 UTC by odow

This PR is a large refactoring of the C code in SCS.jl and fixes #217. It doesn't touch the MOI wrapper. 

There is now a single `_SCSDataWrapper` struct which prevents stuff from being GC'd, and there is now a single `_unsafe_scs_solve` function in which the pointer stuff takes place. 

It also explicitly refactors the linear solvers into three files, and removes all the nasty `@eval` code.

I've marked this as v0.8.0, but we should hold off tagging a new release until we update MOI as well.

2021-09-13 10:00 UTC, kalmarek requested changes
I took a short look at the changes and I'm fine with those;

I left one small comment on `_to_sparse`.

A few additional points:
 * in scs-3.0.0 `scsint_t` would become a `ccall`
 * when we drop julia-1.0 (hopefully soon) and jump to the new LTS the ccalls could be made fully dynamic (aka non-constant function specifications) and then we could merge all separate solvers code again.

2021-09-13 10:03 UTC, kalmarek commented
> It removes all exported functions except `SCS_solve`. We don't want users touching the other functions because there's too much room for GC errors.

I always forgot to remove those exports ;)

> It also explicitly refactors the linear solvers into three files, and removes all the nasty @eval code.

I like `@eval`s ;) and when we drop old julias and move to dynamically generated ccalls these three files could be merged again ;)

2021-09-13 10:15 UTC, kalmarek commented on src/MOI_wrapper/matrix.jl
> +    return A.nzval, A.rowval, A.colptr
I've seen similar SparseMatrixCSRtoCSC in MOI: https://github.com/jump-dev/MatrixOptInterface.jl/blob/master/src/sparse_matrix.jl

Do we even need our own copy?

2021-09-13 20:46 UTC, odow commented on src/MOI_wrapper/matrix.jl
> +    return A.nzval, A.rowval, A.colptr
It will be gone in MOI 0.10.

2021-09-13 20:53 UTC, odow commented
Yeah presumably we will update to SCS 3.0 before releasing SCS.jl 1.0. This PR is more to tidy some things up before we attack the MOI wrapper.

2021-09-13 23:09 UTC, odow commented
Merging because I need this to work on the MOI PR. We can fix any issues in a separate PR; we won't be tagging a new release immediately.

2021-09-13 23:09 UTC, merged

2021-09-14 14:34 UTC, kalmarek commented
@odow I don't want to hold back your work on MOI, so merge stuff at will; I hope to find more time next week to rework SCS-3.0.0 PR and then dive deep into all the changes