WIP: [breaking] refactor linear solver loading to use Pkg extensions
jump-dev/SCS.jl pull request #286
Opened 2023-11-13 01:50 UTC by odow

- [ ] CI will be broken until at least https://github.com/JuliaPackaging/Yggdrasil/pull/7665

2023-11-13 11:01 UTC, kalmarek commented
@odow looks rather good, no more requires, init etc, much cleaner;

I'd suggest however to wait with this until the a new LTS is released which does support extensions. In some sense the current situation, while not optimal just works, and I don't feel like putting more burden of maintaining two incompatible versions of SCS.jl

2023-11-14 02:59 UTC, odow commented on src/SCS.jl
> +SCS.is_available(::Type{<:LinearSolver}) = false
```suggestion
is_available(::Type{<:LinearSolver}) = false
```

2023-11-14 03:58 UTC, odow commented on ext/SCSSCS_GPU_jllExt.jl
> +    )::Cvoid,
```suggestion
    )::Cvoid
```

2023-11-14 04:56 UTC, odow commented
@kalmarek I'm trying to sort it so that we support `@requires` on 1.6 and the package extensions on 1.9. 

We'll still have to do a breaking change to the use package loading, but that's okay. When 1.9 becomes the LTS, we can drop the requires part.

2023-11-14 04:57 UTC, odow commented on README.md
> +**SCS v2.0 introduced a breaking change. You now need to use `SCS_GPU_jll`
```suggestion
**SCS.jl v2.0 introduced a breaking change. You now need to use `SCS_GPU_jll`
```

2023-11-14 04:58 UTC, odow commented on README.md
> +**SCS v2.0 introduced a breaking change. You now need to use `SCS_MKL_jll`
```suggestion
**SCS.jl v2.0 introduced a breaking change. You now need to use `SCS_MKL_jll`
```

2023-11-14 14:18 UTC, kalmarek requested changes
Looks great!

2023-11-14 19:42 UTC, odow commented on src/SCS.jl
> +end
Yeah that didn't work

2023-11-14 19:45 UTC, odow commented
cc @blegat you should take a look at this. Nominally it's a breaking change, but it affects only the lazy loading of the MKL and GPU solvers.

2023-11-15 13:24 UTC, kalmarek approved these changes

2023-11-20 12:19 UTC, blegat approved these changes

2023-11-20 19:31 UTC, merged